apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: github-webapp
images:
- name: ghcr.io/CMarquetand/webapp
  newTag: a7941d80035fee9d62e3c49f23e1a516007b898f
- name: ghcr.io/cmarquetand/webapp
  newTag: e8cb03e
